//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5._2___StoreFront_WPF.StoreServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/_5._2___StoreService.Model")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                if ((this.stockField.Equals(value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/_5._2___StoreService.Model")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<_5._2___StoreFront_WPF.StoreServiceReference.Product, int> productsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double saldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<_5._2___StoreFront_WPF.StoreServiceReference.Product, int> products {
            get {
                return this.productsField;
            }
            set {
                if ((object.ReferenceEquals(this.productsField, value) != true)) {
                    this.productsField = value;
                    this.RaisePropertyChanged("products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double saldo {
            get {
                return this.saldoField;
            }
            set {
                if ((this.saldoField.Equals(value) != true)) {
                    this.saldoField = value;
                    this.RaisePropertyChanged("saldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StoreServiceReference.IStoreService")]
    public interface IStoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/GetProducts", ReplyAction="http://tempuri.org/IStoreService/GetProductsResponse")]
        _5._2___StoreFront_WPF.StoreServiceReference.Product[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/GetProducts", ReplyAction="http://tempuri.org/IStoreService/GetProductsResponse")]
        System.Threading.Tasks.Task<_5._2___StoreFront_WPF.StoreServiceReference.Product[]> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/AddProduct", ReplyAction="http://tempuri.org/IStoreService/AddProductResponse")]
        void AddProduct(string pName, double pPrice, int pStock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/AddProduct", ReplyAction="http://tempuri.org/IStoreService/AddProductResponse")]
        System.Threading.Tasks.Task AddProductAsync(string pName, double pPrice, int pStock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/AddProductToInventory", ReplyAction="http://tempuri.org/IStoreService/AddProductToInventoryResponse")]
        string AddProductToInventory(_5._2___StoreFront_WPF.StoreServiceReference.User buyer, _5._2___StoreFront_WPF.StoreServiceReference.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/AddProductToInventory", ReplyAction="http://tempuri.org/IStoreService/AddProductToInventoryResponse")]
        System.Threading.Tasks.Task<string> AddProductToInventoryAsync(_5._2___StoreFront_WPF.StoreServiceReference.User buyer, _5._2___StoreFront_WPF.StoreServiceReference.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/getInventory", ReplyAction="http://tempuri.org/IStoreService/getInventoryResponse")]
        System.Collections.Generic.Dictionary<_5._2___StoreFront_WPF.StoreServiceReference.Product, int> getInventory(_5._2___StoreFront_WPF.StoreServiceReference.User buyer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/getInventory", ReplyAction="http://tempuri.org/IStoreService/getInventoryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<_5._2___StoreFront_WPF.StoreServiceReference.Product, int>> getInventoryAsync(_5._2___StoreFront_WPF.StoreServiceReference.User buyer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/getProductByName", ReplyAction="http://tempuri.org/IStoreService/getProductByNameResponse")]
        _5._2___StoreFront_WPF.StoreServiceReference.Product getProductByName(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/getProductByName", ReplyAction="http://tempuri.org/IStoreService/getProductByNameResponse")]
        System.Threading.Tasks.Task<_5._2___StoreFront_WPF.StoreServiceReference.Product> getProductByNameAsync(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/GetUserByName", ReplyAction="http://tempuri.org/IStoreService/GetUserByNameResponse")]
        _5._2___StoreFront_WPF.StoreServiceReference.User GetUserByName(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/GetUserByName", ReplyAction="http://tempuri.org/IStoreService/GetUserByNameResponse")]
        System.Threading.Tasks.Task<_5._2___StoreFront_WPF.StoreServiceReference.User> GetUserByNameAsync(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/Register", ReplyAction="http://tempuri.org/IStoreService/RegisterResponse")]
        bool Register(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/Register", ReplyAction="http://tempuri.org/IStoreService/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/Login", ReplyAction="http://tempuri.org/IStoreService/LoginResponse")]
        _5._2___StoreFront_WPF.StoreServiceReference.User Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/Login", ReplyAction="http://tempuri.org/IStoreService/LoginResponse")]
        System.Threading.Tasks.Task<_5._2___StoreFront_WPF.StoreServiceReference.User> LoginAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStoreServiceChannel : _5._2___StoreFront_WPF.StoreServiceReference.IStoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreServiceClient : System.ServiceModel.ClientBase<_5._2___StoreFront_WPF.StoreServiceReference.IStoreService>, _5._2___StoreFront_WPF.StoreServiceReference.IStoreService {
        
        public StoreServiceClient() {
        }
        
        public StoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public _5._2___StoreFront_WPF.StoreServiceReference.Product[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<_5._2___StoreFront_WPF.StoreServiceReference.Product[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public void AddProduct(string pName, double pPrice, int pStock) {
            base.Channel.AddProduct(pName, pPrice, pStock);
        }
        
        public System.Threading.Tasks.Task AddProductAsync(string pName, double pPrice, int pStock) {
            return base.Channel.AddProductAsync(pName, pPrice, pStock);
        }
        
        public string AddProductToInventory(_5._2___StoreFront_WPF.StoreServiceReference.User buyer, _5._2___StoreFront_WPF.StoreServiceReference.Product product) {
            return base.Channel.AddProductToInventory(buyer, product);
        }
        
        public System.Threading.Tasks.Task<string> AddProductToInventoryAsync(_5._2___StoreFront_WPF.StoreServiceReference.User buyer, _5._2___StoreFront_WPF.StoreServiceReference.Product product) {
            return base.Channel.AddProductToInventoryAsync(buyer, product);
        }
        
        public System.Collections.Generic.Dictionary<_5._2___StoreFront_WPF.StoreServiceReference.Product, int> getInventory(_5._2___StoreFront_WPF.StoreServiceReference.User buyer) {
            return base.Channel.getInventory(buyer);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<_5._2___StoreFront_WPF.StoreServiceReference.Product, int>> getInventoryAsync(_5._2___StoreFront_WPF.StoreServiceReference.User buyer) {
            return base.Channel.getInventoryAsync(buyer);
        }
        
        public _5._2___StoreFront_WPF.StoreServiceReference.Product getProductByName(string s) {
            return base.Channel.getProductByName(s);
        }
        
        public System.Threading.Tasks.Task<_5._2___StoreFront_WPF.StoreServiceReference.Product> getProductByNameAsync(string s) {
            return base.Channel.getProductByNameAsync(s);
        }
        
        public _5._2___StoreFront_WPF.StoreServiceReference.User GetUserByName(string s) {
            return base.Channel.GetUserByName(s);
        }
        
        public System.Threading.Tasks.Task<_5._2___StoreFront_WPF.StoreServiceReference.User> GetUserByNameAsync(string s) {
            return base.Channel.GetUserByNameAsync(s);
        }
        
        public bool Register(string username) {
            return base.Channel.Register(username);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(string username) {
            return base.Channel.RegisterAsync(username);
        }
        
        public _5._2___StoreFront_WPF.StoreServiceReference.User Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<_5._2___StoreFront_WPF.StoreServiceReference.User> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
    }
}
